server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: spring-boot-demo
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/cat?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.demo.entity