package com.demo.entity;

import java.util.Date;

public class MobileTagValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.domain
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.item_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.tag_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.tag_value
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private String tagValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.description
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.status
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_tag_value.updatetime
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.id
     *
     * @return the value of mobile_tag_value.id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.id
     *
     * @param id the value for mobile_tag_value.id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.domain
     *
     * @return the value of mobile_tag_value.domain
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.domain
     *
     * @param domain the value for mobile_tag_value.domain
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.item_id
     *
     * @return the value of mobile_tag_value.item_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.item_id
     *
     * @param itemId the value for mobile_tag_value.item_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.tag_id
     *
     * @return the value of mobile_tag_value.tag_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.tag_id
     *
     * @param tagId the value for mobile_tag_value.tag_id
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.tag_value
     *
     * @return the value of mobile_tag_value.tag_value
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public String getTagValue() {
        return tagValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.tag_value
     *
     * @param tagValue the value for mobile_tag_value.tag_value
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setTagValue(String tagValue) {
        this.tagValue = tagValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.description
     *
     * @return the value of mobile_tag_value.description
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.description
     *
     * @param description the value for mobile_tag_value.description
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.status
     *
     * @return the value of mobile_tag_value.status
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.status
     *
     * @param status the value for mobile_tag_value.status
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_tag_value.updatetime
     *
     * @return the value of mobile_tag_value.updatetime
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_tag_value.updatetime
     *
     * @param updatetime the value for mobile_tag_value.updatetime
     *
     * @mbg.generated Wed Jul 10 19:12:21 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        return "MobileTagValue{" +
                "id=" + id +
                ", domain='" + domain + '\'' +
                ", itemId='" + itemId + '\'' +
                ", tagId=" + tagId +
                ", tagValue='" + tagValue + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                ", updatetime=" + updatetime +
                '}';
    }
}